// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShortener.Database;

#nullable disable

namespace UrlShortener.Migrations
{
    [DbContext(typeof(DbConnection))]
    [Migration("20231030180217_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UrlShortener.Models.Address", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Shortned")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Url", "Shortned");

                    b.ToTable("addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
